############################
## CHANGE THESE
############################

baseURL: 'https://labrunning.github.io/qubt'
title: Lumbini

############################
## MISC
############################

enableEmoji: true
disableKinds: ['taxonomy', 'term']
languageCode: 'en-us'


