############################
## Navbar
############################

main:
- name: Home
  url: /
  weight: 10
- name: Wishlist
  url: /wishlist/
  weight: 20
# - name: Blog
#   url: /blog/
#   weight: 30
- name: About
  url: /about/
  weight: 40